### ISSUE TITLE
Not any uninstall script?

### ISSUE THREAD

**Issue by ali-bahjati** [viljoviitanen/setup-simple-pptp-vpn#4]
I would appreciate if you add a uninstall script too

**Comment by viljoviitanen** [comment]
Why?

**Comment by ali-bahjati** [comment]
Cause maybe doesn't work for someone like me (I don't know why but I guess my country has blocked pptp connections) or maybe someone need to reinstall the script

**Comment by viljoviitanen** [comment]
Uninstall: apt-get remove pptpd and manually remove the few lines the script installs in /etc/rc.local file.
