### ISSUE TITLE
No internet connection on aliyun cloud service.

### ISSUE THREAD

**Issue by taekubz** [viljoviitanen/setup-simple-pptp-vpn#8]
The script works fine on digital ocean but there is a problem on aliyun even that I can connect to the server using ubuntu 14. Is there some modification that is needed?

**Comment by viljoviitanen** [comment]
I'm sorry, I don't provide free tech support. Closing the issue.

**Comment by sky93** [comment]
Yes same here. The script doesn't work anymore. I deleted it and configured myself. You have to manually config vpn.
